ALTER TYPE "AuditEvent" ADD VALUE IF NOT EXISTS 'QR_DETECTION_SUCCESS';
ALTER TYPE "AuditEvent" ADD VALUE IF NOT EXISTS 'QR_DETECTION_FAILURE';
ALTER TYPE "AuditEvent" ADD VALUE IF NOT EXISTS 'QR_MANUAL_SELECTION';
