// Owns the public terms page.
// Defines baseline responsibilities for authorized document owners.
// Must stay conservative until formal legal review exists.
import type { Metadata } from "next";

import { PublicShell } from "@/components/layout/public-shell";
import { LegalPage } from "@/components/shared/legal-page";

export const metadata: Metadata = {
  title: "Terms",
  description:
    "Terms for authorized use of Secure PDF QR document processing and access management.",
};

export default function TermsPage() {
  return (
    <PublicShell>
      <LegalPage
        eyebrow="Terms"
        title="Use the platform responsibly and only with proper authority."
        description="These terms describe the expected use of Secure PDF QR as an owner-controlled document processing and access-management tool."
        sections={[
          {
            title: "Permitted purpose",
            body: (
              <p>
                The service is intended for personal, internal, or otherwise
                authorized storage and access management of PDFs. You are
                responsible for confirming that your use is lawful and allowed
                for each document you upload or process.
              </p>
            ),
          },
          {
            title: "Prohibited conduct",
            body: (
              <p>
                You may not use the service for fraud, forgery, falsification,
                impersonation, unlawful modification, evasion of required
                approvals, or any activity that misrepresents the origin,
                status, meaning, or approval of a document.
              </p>
            ),
          },
          {
            title: "Owner-controlled access",
            body: (
              <p>
                QR codes generated by the platform must resolve through
                app-controlled verification, open, or download routes. Access
                may depend on owner-defined settings such as expiration,
                revocation, access limits, and PIN requirements when those
                features are enabled.
              </p>
            ),
          },
          {
            title: "No official status",
            body: (
              <p>
                The service does not provide legal advice, certification,
                notarization, issuer validation, government approval, or any
                guarantee that a document will be accepted by a third party.
              </p>
            ),
          },
        ]}
      />
    </PublicShell>
  );
}
